import "./globals.css";
import FooterServer from "@/components/globals/footer/Server";
import HeaderClient from "@/components/globals/header/Client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <HeaderClient />
        {children}
        <FooterServer />
      </body>
    </html>
  );
}
